# Reference: https://osdev-jp.readthedocs.io/ja/latest/2017/create-uefi-app-with-edk2.html#dsc

[Defines]
  PLATFORM_NAME              = Edk2LibcForDotNet
  PLATFORM_GUID              = 54cf6219-7bf2-45de-9e88-ae71117853ac
  PLATFORM_VERSION           = 6.0.7
  DSC_SPECIFICATION          = 0x00010006
  OUTPUT_DIRECTORY           = Build/Edk2LibcForDotNet
  SUPPORTED_ARCHITECTURES    = X64|IA32|ARM|AARCH64
  BUILD_TARGETS              = RELEASE

[LibraryClasses]
  mp1|MdePkg/Library/BaseCacheMaintenanceLib/BaseCacheMaintenanceLib.inf
  mp2|MdePkg/Library/BaseCacheMaintenanceLibNull/BaseCacheMaintenanceLibNull.inf
  mp3|MdePkg/Library/BaseCpuLib/BaseCpuLib.inf
  mp4|MdePkg/Library/BaseCpuLibNull/BaseCpuLibNull.inf
  mp5|MdePkg/Library/BaseDebugLibNull/BaseDebugLibNull.inf
  mp6|MdePkg/Library/BaseDebugLibSerialPort/BaseDebugLibSerialPort.inf
  mp7|MdePkg/Library/BaseDebugPrintErrorLevelLib/BaseDebugPrintErrorLevelLib.inf
  mp8|MdePkg/Library/BaseExtractGuidedSectionLib/BaseExtractGuidedSectionLib.inf
  mp9|MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic.inf
  mp10|MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsicArmVirt.inf
  mp11|MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsicSev.inf
  mp12|MdePkg/Library/BaseLib/BaseLib.inf
  mp13|MdePkg/Library/BaseLib/UnitTestHostBaseLib.inf
  mp14|MdePkg/Library/BaseMemoryLib/BaseMemoryLib.inf
  mp15|MdePkg/Library/BaseMemoryLibMmx/BaseMemoryLibMmx.inf
  mp16|MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe.inf
  mp17|MdePkg/Library/BaseMemoryLibOptPei/BaseMemoryLibOptPei.inf
  mp18|MdePkg/Library/BaseMemoryLibRepStr/BaseMemoryLibRepStr.inf
  mp19|MdePkg/Library/BaseMemoryLibSse2/BaseMemoryLibSse2.inf
  mp20|MdePkg/Library/BaseOrderedCollectionRedBlackTreeLib/BaseOrderedCollectionRedBlackTreeLib.inf
  mp21|MdePkg/Library/BasePcdLibNull/BasePcdLibNull.inf
  mp22|MdePkg/Library/BasePciCf8Lib/BasePciCf8Lib.inf
  mp23|MdePkg/Library/BasePciExpressLib/BasePciExpressLib.inf
  mp24|MdePkg/Library/BasePciLibCf8/BasePciLibCf8.inf
  mp25|MdePkg/Library/BasePciLibPciExpress/BasePciLibPciExpress.inf
  mp26|MdePkg/Library/BasePciSegmentInfoLibNull/BasePciSegmentInfoLibNull.inf
  mp27|MdePkg/Library/BasePciSegmentLibPci/BasePciSegmentLibPci.inf
  mp28|MdePkg/Library/BasePeCoffExtraActionLibNull/BasePeCoffExtraActionLibNull.inf
  mp29|MdePkg/Library/BasePeCoffGetEntryPointLib/BasePeCoffGetEntryPointLib.inf
  mp30|MdePkg/Library/BasePeCoffLib/BasePeCoffLib.inf
  mp31|MdePkg/Library/BasePerformanceLibNull/BasePerformanceLibNull.inf
  mp32|MdePkg/Library/BasePostCodeLibDebug/BasePostCodeLibDebug.inf
  mp33|MdePkg/Library/BasePostCodeLibPort80/BasePostCodeLibPort80.inf
  mp34|MdePkg/Library/BasePrintLib/BasePrintLib.inf
  mp35|MdePkg/Library/BaseReportStatusCodeLibNull/BaseReportStatusCodeLibNull.inf
  mp36|MdePkg/Library/BaseRngLib/BaseRngLib.inf
  mp37|MdePkg/Library/BaseRngLibNull/BaseRngLibNull.inf
  mp38|MdePkg/Library/BaseRngLibTimerLib/BaseRngLibTimerLib.inf
  mp39|MdePkg/Library/BaseS3BootScriptLibNull/BaseS3BootScriptLibNull.inf
  mp40|MdePkg/Library/BaseS3IoLib/BaseS3IoLib.inf
  mp41|MdePkg/Library/BaseS3PciLib/BaseS3PciLib.inf
  mp42|MdePkg/Library/BaseS3PciSegmentLib/BaseS3PciSegmentLib.inf
  mp43|MdePkg/Library/BaseS3SmbusLib/BaseS3SmbusLib.inf
  mp44|MdePkg/Library/BaseS3StallLib/BaseS3StallLib.inf
  mp45|MdePkg/Library/BaseSafeIntLib/BaseSafeIntLib.inf
  mp46|MdePkg/Library/BaseSerialPortLibNull/BaseSerialPortLibNull.inf
  mp47|MdePkg/Library/BaseSmbusLibNull/BaseSmbusLibNull.inf
  mp48|MdePkg/Library/BaseStackCheckLib/BaseStackCheckLib.inf
  mp49|MdePkg/Library/BaseSynchronizationLib/BaseSynchronizationLib.inf
  mp50|MdePkg/Library/BaseTimerLibNullTemplate/BaseTimerLibNullTemplate.inf
  mp51|MdePkg/Library/BaseUefiDecompressLib/BaseUefiDecompressLib.inf
  mp52|MdePkg/Library/BaseUefiDecompressLib/BaseUefiTianoCustomDecompressLib.inf
  mp53|MdePkg/Library/DxeCoreEntryPoint/DxeCoreEntryPoint.inf
  mp54|MdePkg/Library/DxeCoreHobLib/DxeCoreHobLib.inf
  mp55|MdePkg/Library/DxeExtractGuidedSectionLib/DxeExtractGuidedSectionLib.inf
  mp56|MdePkg/Library/DxeHobLib/DxeHobLib.inf
  mp57|MdePkg/Library/DxeHstiLib/DxeHstiLib.inf
  mp58|MdePkg/Library/DxeIoLibCpuIo2/DxeIoLibCpuIo2.inf
  mp59|MdePkg/Library/DxePcdLib/DxePcdLib.inf
  mp60|MdePkg/Library/DxeRngLib/DxeRngLib.inf
  mp61|MdePkg/Library/DxeRuntimeDebugLibSerialPort/DxeRuntimeDebugLibSerialPort.inf
  mp62|MdePkg/Library/DxeRuntimePciExpressLib/DxeRuntimePciExpressLib.inf
  mp63|MdePkg/Library/DxeServicesLib/DxeServicesLib.inf
  mp64|MdePkg/Library/DxeServicesTableLib/DxeServicesTableLib.inf
  mp65|MdePkg/Library/DxeSmbusLib/DxeSmbusLib.inf
  mp66|MdePkg/Library/MmServicesTableLib/MmServicesTableLib.inf
  mp67|MdePkg/Library/MmUnblockMemoryLib/MmUnblockMemoryLibNull.inf
  mp68|MdePkg/Library/PciSegmentLibSegmentInfo/BasePciSegmentLibSegmentInfo.inf
  mp69|MdePkg/Library/PciSegmentLibSegmentInfo/DxeRuntimePciSegmentLibSegmentInfo.inf
  mp70|MdePkg/Library/PeiCoreEntryPoint/PeiCoreEntryPoint.inf
  mp71|MdePkg/Library/PeiDxePostCodeLibReportStatusCode/PeiDxePostCodeLibReportStatusCode.inf
  mp72|MdePkg/Library/PeiExtractGuidedSectionLib/PeiExtractGuidedSectionLib.inf
  mp73|MdePkg/Library/PeiHobLib/PeiHobLib.inf
  mp74|MdePkg/Library/PeiIoLibCpuIo/PeiIoLibCpuIo.inf
  mp75|MdePkg/Library/PeiMemoryAllocationLib/PeiMemoryAllocationLib.inf
  mp76|MdePkg/Library/PeiMemoryLib/PeiMemoryLib.inf
  mp77|MdePkg/Library/PeimEntryPoint/PeimEntryPoint.inf
  mp78|MdePkg/Library/PeiPcdLib/PeiPcdLib.inf
  mp79|MdePkg/Library/PeiPciLibPciCfg2/PeiPciLibPciCfg2.inf
  mp80|MdePkg/Library/PeiPciSegmentLibPciCfg2/PeiPciSegmentLibPciCfg2.inf
  mp81|MdePkg/Library/PeiResourcePublicationLib/PeiResourcePublicationLib.inf
  mp82|MdePkg/Library/PeiServicesLib/PeiServicesLib.inf
  mp83|MdePkg/Library/PeiServicesTablePointerLib/PeiServicesTablePointerLib.inf
  mp84|MdePkg/Library/PeiServicesTablePointerLibIdt/PeiServicesTablePointerLibIdt.inf
  mp85|MdePkg/Library/PeiSmbusLibSmbus2Ppi/PeiSmbusLibSmbus2Ppi.inf
  mp86|MdePkg/Library/RegisterFilterLibNull/RegisterFilterLibNull.inf
  mp87|MdePkg/Library/SecPeiDxeTimerLibCpu/SecPeiDxeTimerLibCpu.inf
  mp88|MdePkg/Library/SmiHandlerProfileLibNull/SmiHandlerProfileLibNull.inf
  mp89|MdePkg/Library/SmmIoLib/SmmIoLib.inf
  mp90|MdePkg/Library/SmmIoLibSmmCpuIo2/SmmIoLibSmmCpuIo2.inf
  mp91|MdePkg/Library/SmmLibNull/SmmLibNull.inf
  mp92|MdePkg/Library/SmmMemLib/SmmMemLib.inf
  mp93|MdePkg/Library/SmmMemoryAllocationLib/SmmMemoryAllocationLib.inf
  mp94|MdePkg/Library/SmmPciExpressLib/SmmPciExpressLib.inf
  mp95|MdePkg/Library/SmmPciLibPciRootBridgeIo/SmmPciLibPciRootBridgeIo.inf
  mp96|MdePkg/Library/SmmPeriodicSmiLib/SmmPeriodicSmiLib.inf
  mp97|MdePkg/Library/SmmServicesTableLib/SmmServicesTableLib.inf
  mp98|MdePkg/Library/StandaloneMmDriverEntryPoint/StandaloneMmDriverEntryPoint.inf
  mp99|MdePkg/Library/StandaloneMmServicesTableLib/StandaloneMmServicesTableLib.inf
  mp100|MdePkg/Library/UefiApplicationEntryPoint/UefiApplicationEntryPoint.inf
  mp101|MdePkg/Library/UefiBootServicesTableLib/UefiBootServicesTableLib.inf
  mp102|MdePkg/Library/UefiDebugLibConOut/UefiDebugLibConOut.inf
  mp103|MdePkg/Library/UefiDebugLibDebugPortProtocol/UefiDebugLibDebugPortProtocol.inf
  mp104|MdePkg/Library/UefiDebugLibStdErr/UefiDebugLibStdErr.inf
  mp105|MdePkg/Library/UefiDevicePathLib/UefiDevicePathLib.inf
  mp106|MdePkg/Library/UefiDevicePathLib/UefiDevicePathLibOptionalDevicePathProtocol.inf
  mp107|MdePkg/Library/UefiDevicePathLib/UefiDevicePathLibStandaloneMm.inf
  mp108|MdePkg/Library/UefiDevicePathLibDevicePathProtocol/UefiDevicePathLibDevicePathProtocol.inf
  mp109|MdePkg/Library/UefiDriverEntryPoint/UefiDriverEntryPoint.inf
  mp110|MdePkg/Library/UefiFileHandleLib/UefiFileHandleLib.inf
  mp111|MdePkg/Library/UefiLib/UefiLib.inf
  mp112|MdePkg/Library/UefiMemoryAllocationLib/UefiMemoryAllocationLib.inf
  mp113|MdePkg/Library/UefiMemoryLib/UefiMemoryLib.inf
  mp114|MdePkg/Library/UefiPciLibPciRootBridgeIo/UefiPciLibPciRootBridgeIo.inf
  mp115|MdePkg/Library/UefiPciSegmentLibPciRootBridgeIo/UefiPciSegmentLibPciRootBridgeIo.inf
  mp116|MdePkg/Library/UefiRuntimeLib/UefiRuntimeLib.inf
  mp117|MdePkg/Library/UefiRuntimeServicesTableLib/UefiRuntimeServicesTableLib.inf
  mp118|MdePkg/Library/UefiScsiLib/UefiScsiLib.inf
  mp119|MdePkg/Library/UefiUsbLib/UefiUsbLib.inf
  mp120|MdePkg/Test/UnitTest/Library/BaseLib/BaseLibUnitTestsHost.inf
  mp121|MdePkg/Test/UnitTest/Library/BaseLib/BaseLibUnitTestsUefi.inf
  mp122|MdePkg/Test/UnitTest/Library/BaseSafeIntLib/TestBaseSafeIntLibDxe.inf
  mp123|MdePkg/Test/UnitTest/Library/BaseSafeIntLib/TestBaseSafeIntLibHost.inf
  mp124|MdePkg/Test/UnitTest/Library/BaseSafeIntLib/TestBaseSafeIntLibPei.inf
  mp125|MdePkg/Test/UnitTest/Library/BaseSafeIntLib/TestBaseSafeIntLibSmm.inf
  mp126|MdePkg/Test/UnitTest/Library/BaseSafeIntLib/TestBaseSafeIntLibUefiShell.inf
  mmp1|MdeModulePkg/Application/BootManagerMenuApp/BootManagerMenuApp.inf
  mmp2|MdeModulePkg/Application/CapsuleApp/CapsuleApp.inf
  mmp3|MdeModulePkg/Application/DumpDynPcd/DumpDynPcd.inf
  mmp4|MdeModulePkg/Application/HelloWorld/HelloWorld.inf
  mmp5|MdeModulePkg/Application/MemoryProfileInfo/MemoryProfileInfo.inf
  mmp6|MdeModulePkg/Application/SmiHandlerProfileInfo/SmiHandlerProfileInfo.inf
  mmp7|MdeModulePkg/Application/UiApp/UiApp.inf
  mmp8|MdeModulePkg/Application/VariableInfo/VariableInfo.inf
  mmp9|MdeModulePkg/Bus/Ata/AhciPei/AhciPei.inf
  mmp10|MdeModulePkg/Bus/Ata/AtaAtapiPassThru/AtaAtapiPassThru.inf
  mmp11|MdeModulePkg/Bus/Ata/AtaBusDxe/AtaBusDxe.inf
  mmp12|MdeModulePkg/Bus/I2c/I2cDxe/I2cBusDxe.inf
  mmp13|MdeModulePkg/Bus/I2c/I2cDxe/I2cDxe.inf
  mmp14|MdeModulePkg/Bus/I2c/I2cDxe/I2cHostDxe.inf
  mmp15|MdeModulePkg/Bus/Isa/IsaBusDxe/IsaBusDxe.inf
  mmp16|MdeModulePkg/Bus/Isa/Ps2KeyboardDxe/Ps2KeyboardDxe.inf
  mmp17|MdeModulePkg/Bus/Isa/Ps2MouseDxe/Ps2MouseDxe.inf
  mmp18|MdeModulePkg/Bus/Pci/EhciDxe/EhciDxe.inf
  mmp19|MdeModulePkg/Bus/Pci/EhciPei/EhciPei.inf
  mmp20|MdeModulePkg/Bus/Pci/IdeBusPei/IdeBusPei.inf
  mmp21|MdeModulePkg/Bus/Pci/IncompatiblePciDeviceSupportDxe/IncompatiblePciDeviceSupportDxe.inf
  mmp22|MdeModulePkg/Bus/Pci/NonDiscoverablePciDeviceDxe/NonDiscoverablePciDeviceDxe.inf
  mmp23|MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressDxe.inf
  mmp24|MdeModulePkg/Bus/Pci/NvmExpressPei/NvmExpressPei.inf
  mmp25|MdeModulePkg/Bus/Pci/PciBusDxe/PciBusDxe.inf
  mmp26|MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostBridgeDxe.inf
  mmp27|MdeModulePkg/Bus/Pci/PciSioSerialDxe/PciSioSerialDxe.inf
  mmp28|MdeModulePkg/Bus/Pci/SataControllerDxe/SataControllerDxe.inf
  mmp29|MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHcDxe.inf
  mmp30|MdeModulePkg/Bus/Pci/SdMmcPciHcPei/SdMmcPciHcPei.inf
  mmp31|MdeModulePkg/Bus/Pci/UfsPciHcDxe/UfsPciHcDxe.inf
  mmp32|MdeModulePkg/Bus/Pci/UfsPciHcPei/UfsPciHcPei.inf
  mmp33|MdeModulePkg/Bus/Pci/UhciDxe/UhciDxe.inf
  mmp34|MdeModulePkg/Bus/Pci/UhciPei/UhciPei.inf
  mmp35|MdeModulePkg/Bus/Pci/XhciDxe/XhciDxe.inf
  mmp36|MdeModulePkg/Bus/Pci/XhciPei/XhciPei.inf
  mmp37|MdeModulePkg/Bus/Scsi/ScsiBusDxe/ScsiBusDxe.inf
  mmp38|MdeModulePkg/Bus/Scsi/ScsiDiskDxe/ScsiDiskDxe.inf
  mmp39|MdeModulePkg/Bus/Sd/EmmcBlockIoPei/EmmcBlockIoPei.inf
  mmp40|MdeModulePkg/Bus/Sd/EmmcDxe/EmmcDxe.inf
  mmp41|MdeModulePkg/Bus/Sd/SdBlockIoPei/SdBlockIoPei.inf
  mmp42|MdeModulePkg/Bus/Sd/SdDxe/SdDxe.inf
  mmp43|MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsBlockIoPei.inf
  mmp44|MdeModulePkg/Bus/Ufs/UfsPassThruDxe/UfsPassThruDxe.inf
  mmp45|MdeModulePkg/Bus/Usb/UsbBotPei/UsbBotPei.inf
  mmp46|MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBusDxe.inf
  mmp47|MdeModulePkg/Bus/Usb/UsbBusPei/UsbBusPei.inf
  mmp48|MdeModulePkg/Bus/Usb/UsbKbDxe/UsbKbDxe.inf
  mmp49|MdeModulePkg/Bus/Usb/UsbMassStorageDxe/UsbMassStorageDxe.inf
  mmp50|MdeModulePkg/Bus/Usb/UsbMouseAbsolutePointerDxe/UsbMouseAbsolutePointerDxe.inf
  mmp51|MdeModulePkg/Bus/Usb/UsbMouseDxe/UsbMouseDxe.inf
  mmp52|MdeModulePkg/Core/Dxe/DxeMain.inf
  mmp53|MdeModulePkg/Core/DxeIplPeim/DxeIpl.inf
  mmp54|MdeModulePkg/Core/Pei/PeiMain.inf
  mmp55|MdeModulePkg/Core/PiSmmCore/PiSmmCore.inf
  mmp56|MdeModulePkg/Core/PiSmmCore/PiSmmIpl.inf
  mmp57|MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
  mmp58|MdeModulePkg/Library/AuthVariableLibNull/AuthVariableLibNull.inf
  mmp59|MdeModulePkg/Library/BaseBmpSupportLib/BaseBmpSupportLib.inf
  mmp60|MdeModulePkg/Library/BaseHobLibNull/BaseHobLibNull.inf
  mmp61|MdeModulePkg/Library/BaseIpmiLibNull/BaseIpmiLibNull.inf
  mmp62|MdeModulePkg/Library/BaseMemoryAllocationLibNull/BaseMemoryAllocationLibNull.inf
  mmp63|MdeModulePkg/Library/BasePlatformHookLibNull/BasePlatformHookLibNull.inf
  mmp64|MdeModulePkg/Library/BaseResetSystemLibNull/BaseResetSystemLibNull.inf
  mmp65|MdeModulePkg/Library/BaseSerialPortLib16550/BaseSerialPortLib16550.inf
  mmp66|MdeModulePkg/Library/BaseSortLib/BaseSortLib.inf
  mmp67|MdeModulePkg/Library/BootDiscoveryPolicyUiLib/BootDiscoveryPolicyUiLib.inf
  mmp68|MdeModulePkg/Library/BootLogoLib/BootLogoLib.inf
  mmp69|MdeModulePkg/Library/BootMaintenanceManagerUiLib/BootMaintenanceManagerUiLib.inf
  mmp70|MdeModulePkg/Library/BootManagerUiLib/BootManagerUiLib.inf
  mmp71|MdeModulePkg/Library/BrotliCustomDecompressLib/BrotliCustomDecompressLib.inf
  mmp72|MdeModulePkg/Library/CpuExceptionHandlerLibNull/CpuExceptionHandlerLibNull.inf
  mmp73|MdeModulePkg/Library/CustomizedDisplayLib/CustomizedDisplayLib.inf
  mmp74|MdeModulePkg/Library/DebugAgentLibNull/DebugAgentLibNull.inf
  mmp75|MdeModulePkg/Library/DeviceManagerUiLib/DeviceManagerUiLib.inf
  mmp76|MdeModulePkg/Library/DisplayUpdateProgressLibGraphics/DisplayUpdateProgressLibGraphics.inf
  mmp77|MdeModulePkg/Library/DisplayUpdateProgressLibText/DisplayUpdateProgressLibText.inf
  mmp78|MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.inf
  mmp79|MdeModulePkg/Library/DxeCapsuleLibFmp/DxeRuntimeCapsuleLib.inf
  mmp80|MdeModulePkg/Library/DxeCapsuleLibNull/DxeCapsuleLibNull.inf
  mmp81|MdeModulePkg/Library/DxeCoreMemoryAllocationLib/DxeCoreMemoryAllocationLib.inf
  mmp82|MdeModulePkg/Library/DxeCoreMemoryAllocationLib/DxeCoreMemoryAllocationProfileLib.inf
  mmp83|MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.inf
  mmp84|MdeModulePkg/Library/DxeCrc32GuidedSectionExtractLib/DxeCrc32GuidedSectionExtractLib.inf
  mmp85|MdeModulePkg/Library/DxeDebugPrintErrorLevelLib/DxeDebugPrintErrorLevelLib.inf
  mmp86|MdeModulePkg/Library/DxeFileExplorerProtocol/DxeFileExplorerProtocol.inf
  mmp87|MdeModulePkg/Library/DxeIpmiLibIpmiProtocol/DxeIpmiLibIpmiProtocol.inf
  mmp88|MdeModulePkg/Library/DxePerformanceLib/DxePerformanceLib.inf
  mmp89|MdeModulePkg/Library/DxePrintLibPrint2Protocol/DxePrintLibPrint2Protocol.inf
  mmp90|MdeModulePkg/Library/DxeReportStatusCodeLib/DxeReportStatusCodeLib.inf
  mmp91|MdeModulePkg/Library/DxeResetSystemLib/DxeResetSystemLib.inf
  mmp92|MdeModulePkg/Library/DxeResetSystemLib/UnitTest/DxeResetSystemLibUnitTestHost.inf
  mmp93|MdeModulePkg/Library/DxeResetSystemLib/UnitTest/MockUefiRuntimeServicesTableLib.inf
  mmp94|MdeModulePkg/Library/DxeSecurityManagementLib/DxeSecurityManagementLib.inf
  mmp95|MdeModulePkg/Library/FileExplorerLib/FileExplorerLib.inf
  mmp96|MdeModulePkg/Library/FmpAuthenticationLibNull/FmpAuthenticationLibNull.inf
  mmp97|MdeModulePkg/Library/FrameBufferBltLib/FrameBufferBltLib.inf
  mmp98|MdeModulePkg/Library/LockBoxNullLib/LockBoxNullLib.inf
  mmp99|MdeModulePkg/Library/LzmaCustomDecompressLib/LzmaArchCustomDecompressLib.inf
  mmp100|MdeModulePkg/Library/LzmaCustomDecompressLib/LzmaCustomDecompressLib.inf
  mmp101|MdeModulePkg/Library/NonDiscoverableDeviceRegistrationLib/NonDiscoverableDeviceRegistrationLib.inf
  mmp102|MdeModulePkg/Library/OemHookStatusCodeLibNull/OemHookStatusCodeLibNull.inf
  mmp103|MdeModulePkg/Library/PciHostBridgeLibNull/PciHostBridgeLibNull.inf
  mmp104|MdeModulePkg/Library/PeiCrc32GuidedSectionExtractLib/PeiCrc32GuidedSectionExtractLib.inf
  mmp105|MdeModulePkg/Library/PeiDebugLibDebugPpi/PeiDebugLibDebugPpi.inf
  mmp106|MdeModulePkg/Library/PeiDebugPrintHobLib/PeiDebugPrintHobLib.inf
  mmp107|MdeModulePkg/Library/PeiDxeDebugLibReportStatusCode/PeiDxeDebugLibReportStatusCode.inf
  mmp108|MdeModulePkg/Library/PeiIpmiLibIpmiPpi/PeiIpmiLibIpmiPpi.inf
  mmp109|MdeModulePkg/Library/PeiPerformanceLib/PeiPerformanceLib.inf
  mmp110|MdeModulePkg/Library/PeiReportStatusCodeLib/PeiReportStatusCodeLib.inf
  mmp111|MdeModulePkg/Library/PeiResetSystemLib/PeiResetSystemLib.inf
  mmp112|MdeModulePkg/Library/PiDxeS3BootScriptLib/DxeS3BootScriptLib.inf
  mmp113|MdeModulePkg/Library/PiSmmCoreMemoryAllocationLib/PiSmmCoreMemoryAllocationLib.inf
  mmp114|MdeModulePkg/Library/PiSmmCoreMemoryAllocationLib/PiSmmCoreMemoryAllocationProfileLib.inf
  mmp115|MdeModulePkg/Library/PiSmmCoreSmmServicesTableLib/PiSmmCoreSmmServicesTableLib.inf
  mmp116|MdeModulePkg/Library/PlatformBootManagerLibNull/PlatformBootManagerLibNull.inf
  mmp117|MdeModulePkg/Library/PlatformHookLibSerialPortPpi/PlatformHookLibSerialPortPpi.inf
  mmp118|MdeModulePkg/Library/PlatformVarCleanupLib/PlatformVarCleanupLib.inf
  mmp119|MdeModulePkg/Library/ResetUtilityLib/ResetUtilityLib.inf
  mmp120|MdeModulePkg/Library/RuntimeDxeReportStatusCodeLib/RuntimeDxeReportStatusCodeLib.inf
  mmp121|MdeModulePkg/Library/RuntimeResetSystemLib/RuntimeResetSystemLib.inf
  mmp122|MdeModulePkg/Library/SmmCorePerformanceLib/SmmCorePerformanceLib.inf
  mmp123|MdeModulePkg/Library/SmmCorePlatformHookLibNull/SmmCorePlatformHookLibNull.inf
  mmp124|MdeModulePkg/Library/SmmIpmiLibSmmIpmiProtocol/SmmIpmiLibSmmIpmiProtocol.inf
  mmp125|MdeModulePkg/Library/SmmLockBoxLib/SmmLockBoxDxeLib.inf
  mmp126|MdeModulePkg/Library/SmmLockBoxLib/SmmLockBoxPeiLib.inf
  mmp127|MdeModulePkg/Library/SmmLockBoxLib/SmmLockBoxSmmLib.inf
  mmp128|MdeModulePkg/Library/SmmLockBoxLib/SmmLockBoxStandaloneMmLib.inf
  mmp129|MdeModulePkg/Library/SmmMemoryAllocationProfileLib/SmmMemoryAllocationProfileLib.inf
  mmp130|MdeModulePkg/Library/SmmPerformanceLib/SmmPerformanceLib.inf
  mmp131|MdeModulePkg/Library/SmmReportStatusCodeLib/SmmReportStatusCodeLib.inf
  mmp132|MdeModulePkg/Library/SmmReportStatusCodeLib/StandaloneMmReportStatusCodeLib.inf
  mmp133|MdeModulePkg/Library/SmmSmiHandlerProfileLib/SmmSmiHandlerProfileLib.inf
  mmp134|MdeModulePkg/Library/SmmSmiHandlerProfileLib/StandaloneMmSmiHandlerProfileLib.inf
  mmp135|MdeModulePkg/Library/TpmMeasurementLibNull/TpmMeasurementLibNull.inf
  mmp136|MdeModulePkg/Library/UefiBootManagerLib/UefiBootManagerLib.inf
  mmp137|MdeModulePkg/Library/UefiHiiLib/UefiHiiLib.inf
  mmp138|MdeModulePkg/Library/UefiHiiServicesLib/UefiHiiServicesLib.inf
  mmp139|MdeModulePkg/Library/UefiMemoryAllocationProfileLib/UefiMemoryAllocationProfileLib.inf
  mmp140|MdeModulePkg/Library/UefiSortLib/UefiSortLib.inf
  mmp141|MdeModulePkg/Library/UefiSortLib/UnitTest/UefiSortLibUnitTest.inf
  mmp142|MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLib.inf
  mmp143|MdeModulePkg/Library/VarCheckLib/VarCheckLib.inf
  mmp144|MdeModulePkg/Library/VarCheckPcdLib/VarCheckPcdLib.inf
  mmp145|MdeModulePkg/Library/VarCheckPolicyLib/VarCheckPolicyLib.inf
  mmp146|MdeModulePkg/Library/VarCheckPolicyLib/VarCheckPolicyLibStandaloneMm.inf
  mmp147|MdeModulePkg/Library/VarCheckUefiLib/VarCheckUefiLib.inf
  mmp148|MdeModulePkg/Library/VariablePolicyHelperLib/VariablePolicyHelperLib.inf
  mmp149|MdeModulePkg/Library/VariablePolicyLib/VariablePolicyLib.inf
  mmp150|MdeModulePkg/Library/VariablePolicyLib/VariablePolicyLibRuntimeDxe.inf
  mmp151|MdeModulePkg/Logo/Logo.inf
  mmp152|MdeModulePkg/Logo/LogoDxe.inf
  mmp153|MdeModulePkg/Universal/Acpi/AcpiPlatformDxe/AcpiPlatformDxe.inf
  mmp154|MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableDxe.inf
  mmp155|MdeModulePkg/Universal/Acpi/BootGraphicsResourceTableDxe/BootGraphicsResourceTableDxe.inf
  mmp156|MdeModulePkg/Universal/Acpi/BootScriptExecutorDxe/BootScriptExecutorDxe.inf
  mmp157|MdeModulePkg/Universal/Acpi/FirmwarePerformanceDataTableDxe/FirmwarePerformanceDxe.inf
  mmp158|MdeModulePkg/Universal/Acpi/FirmwarePerformanceDataTablePei/FirmwarePerformancePei.inf
  mmp159|MdeModulePkg/Universal/Acpi/FirmwarePerformanceDataTableSmm/FirmwarePerformanceSmm.inf
  mmp160|MdeModulePkg/Universal/Acpi/FirmwarePerformanceDataTableSmm/FirmwarePerformanceStandaloneMm.inf
  mmp161|MdeModulePkg/Universal/Acpi/S3SaveStateDxe/S3SaveStateDxe.inf
  mmp162|MdeModulePkg/Universal/Acpi/SmmS3SaveState/SmmS3SaveState.inf
  mmp163|MdeModulePkg/Universal/BdsDxe/BdsDxe.inf
  mmp164|MdeModulePkg/Universal/BootManagerPolicyDxe/BootManagerPolicyDxe.inf
  mmp165|MdeModulePkg/Universal/CapsuleOnDiskLoadPei/CapsuleOnDiskLoadPei.inf
  mmp166|MdeModulePkg/Universal/CapsulePei/CapsulePei.inf
  mmp167|MdeModulePkg/Universal/CapsulePei/CapsuleX64.inf
  mmp168|MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
  mmp169|MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
  mmp170|MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
  mmp171|MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
  mmp172|MdeModulePkg/Universal/Console/GraphicsOutputDxe/GraphicsOutputDxe.inf
  mmp173|MdeModulePkg/Universal/Console/TerminalDxe/TerminalDxe.inf
  mmp174|MdeModulePkg/Universal/DebugPortDxe/DebugPortDxe.inf
  mmp175|MdeModulePkg/Universal/DebugServicePei/DebugServicePei.inf
  mmp176|MdeModulePkg/Universal/DebugSupportDxe/DebugSupportDxe.inf
  mmp177|MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
  mmp178|MdeModulePkg/Universal/Disk/CdExpressPei/CdExpressPei.inf
  mmp179|MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
  mmp180|MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
  mmp181|MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe.inf
  mmp182|MdeModulePkg/Universal/Disk/UdfDxe/UdfDxe.inf
  mmp183|MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
  mmp184|MdeModulePkg/Universal/DisplayEngineDxe/DisplayEngineDxe.inf
  mmp185|MdeModulePkg/Universal/DriverHealthManagerDxe/DriverHealthManagerDxe.inf
  mmp186|MdeModulePkg/Universal/DriverSampleDxe/DriverSampleDxe.inf
  mmp187|MdeModulePkg/Universal/EbcDxe/EbcDebugger.inf
  mmp188|MdeModulePkg/Universal/EbcDxe/EbcDebuggerConfig.inf
  mmp189|MdeModulePkg/Universal/EbcDxe/EbcDxe.inf
  mmp190|MdeModulePkg/Universal/EsrtDxe/EsrtDxe.inf
  mmp191|MdeModulePkg/Universal/EsrtFmpDxe/EsrtFmpDxe.inf
  mmp192|MdeModulePkg/Universal/FaultTolerantWriteDxe/FaultTolerantWriteDxe.inf
  mmp193|MdeModulePkg/Universal/FaultTolerantWriteDxe/FaultTolerantWriteSmm.inf
  mmp194|MdeModulePkg/Universal/FaultTolerantWriteDxe/FaultTolerantWriteSmmDxe.inf
  mmp195|MdeModulePkg/Universal/FaultTolerantWriteDxe/FaultTolerantWriteStandaloneMm.inf
  mmp196|MdeModulePkg/Universal/FaultTolerantWritePei/FaultTolerantWritePei.inf
  mmp197|MdeModulePkg/Universal/FileExplorerDxe/FileExplorerDxe.inf
  mmp198|MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
  mmp199|MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
  mmp200|MdeModulePkg/Universal/HiiResourcesSampleDxe/HiiResourcesSampleDxe.inf
  mmp201|MdeModulePkg/Universal/LegacyRegion2Dxe/LegacyRegion2Dxe.inf
  mmp202|MdeModulePkg/Universal/LoadFileOnFv2/LoadFileOnFv2.inf
  mmp203|MdeModulePkg/Universal/LockBox/SmmLockBox/SmmLockBox.inf
  mmp204|MdeModulePkg/Universal/MemoryTest/GenericMemoryTestDxe/GenericMemoryTestDxe.inf
  mmp205|MdeModulePkg/Universal/MemoryTest/NullMemoryTestDxe/NullMemoryTestDxe.inf
  mmp206|MdeModulePkg/Universal/Metronome/Metronome.inf
  mmp207|MdeModulePkg/Universal/MonotonicCounterRuntimeDxe/MonotonicCounterRuntimeDxe.inf
  mmp208|MdeModulePkg/Universal/PcatSingleSegmentPciCfg2Pei/PcatSingleSegmentPciCfg2Pei.inf
  mmp209|MdeModulePkg/Universal/PCD/Dxe/Pcd.inf
  mmp210|MdeModulePkg/Universal/PCD/Pei/Pcd.inf
  mmp211|MdeModulePkg/Universal/PlatformDriOverrideDxe/PlatformDriOverrideDxe.inf
  mmp212|MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
  mmp213|MdeModulePkg/Universal/RegularExpressionDxe/RegularExpressionDxe.inf
  mmp214|MdeModulePkg/Universal/ReportStatusCodeRouter/Pei/ReportStatusCodeRouterPei.inf
  mmp215|MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/ReportStatusCodeRouterRuntimeDxe.inf
  mmp216|MdeModulePkg/Universal/ReportStatusCodeRouter/Smm/ReportStatusCodeRouterSmm.inf
  mmp217|MdeModulePkg/Universal/ReportStatusCodeRouter/Smm/ReportStatusCodeRouterStandaloneMm.inf
  mmp218|MdeModulePkg/Universal/ResetSystemPei/ResetSystemPei.inf
  mmp219|MdeModulePkg/Universal/ResetSystemRuntimeDxe/ResetSystemRuntimeDxe.inf
  mmp220|MdeModulePkg/Universal/SectionExtractionDxe/SectionExtractionDxe.inf
  mmp221|MdeModulePkg/Universal/SectionExtractionPei/SectionExtractionPei.inf
  mmp222|MdeModulePkg/Universal/SecurityStubDxe/SecurityStubDxe.inf
  mmp223|MdeModulePkg/Universal/SerialDxe/SerialDxe.inf
  mmp224|MdeModulePkg/Universal/SetupBrowserDxe/SetupBrowserDxe.inf
  mmp225|MdeModulePkg/Universal/SmbiosDxe/SmbiosDxe.inf
  mmp226|MdeModulePkg/Universal/SmbiosMeasurementDxe/SmbiosMeasurementDxe.inf
  mmp227|MdeModulePkg/Universal/SmmCommunicationBufferDxe/SmmCommunicationBufferDxe.inf
  mmp228|MdeModulePkg/Universal/StatusCodeHandler/Pei/StatusCodeHandlerPei.inf
  mmp229|MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/StatusCodeHandlerRuntimeDxe.inf
  mmp230|MdeModulePkg/Universal/StatusCodeHandler/Smm/StatusCodeHandlerSmm.inf
  mmp231|MdeModulePkg/Universal/StatusCodeHandler/Smm/StatusCodeHandlerStandaloneMm.inf
  mmp232|MdeModulePkg/Universal/TimestampDxe/TimestampDxe.inf
  mmp233|MdeModulePkg/Universal/Variable/Pei/VariablePei.inf
  mmp234|MdeModulePkg/Universal/Variable/RuntimeDxe/RuntimeDxeUnitTest/VariableLockRequestToLockUnitTest.inf
  mmp235|MdeModulePkg/Universal/Variable/RuntimeDxe/VariableRuntimeDxe.inf
  mmp236|MdeModulePkg/Universal/Variable/RuntimeDxe/VariableSmm.inf
  mmp237|MdeModulePkg/Universal/Variable/RuntimeDxe/VariableSmmRuntimeDxe.inf
  mmp238|MdeModulePkg/Universal/Variable/RuntimeDxe/VariableStandaloneMm.inf
  mmp239|MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
  sp1|ShellPkg/Application/AcpiViewApp/AcpiViewApp.inf
  sp2|ShellPkg/Application/Shell/Shell.inf
  sp3|ShellPkg/Application/ShellCTestApp/ShellCTestApp.inf
  sp4|ShellPkg/Application/ShellExecTestApp/SA.inf
  sp5|ShellPkg/Application/ShellSortTestApp/ShellSortTestApp.inf
  sp6|ShellPkg/DynamicCommand/DpDynamicCommand/DpApp.inf
  sp7|ShellPkg/DynamicCommand/DpDynamicCommand/DpDynamicCommand.inf
  sp8|ShellPkg/DynamicCommand/HttpDynamicCommand/HttpApp.inf
  sp9|ShellPkg/DynamicCommand/HttpDynamicCommand/HttpDynamicCommand.inf
  sp10|ShellPkg/DynamicCommand/TftpDynamicCommand/TftpApp.inf
  sp11|ShellPkg/DynamicCommand/TftpDynamicCommand/TftpDynamicCommand.inf
  sp12|ShellPkg/Library/UefiHandleParsingLib/UefiHandleParsingLib.inf
  sp13|ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf
  sp14|ShellPkg/Library/UefiShellBcfgCommandLib/UefiShellBcfgCommandLib.inf
  sp15|ShellPkg/Library/UefiShellCEntryLib/UefiShellCEntryLib.inf
  sp16|ShellPkg/Library/UefiShellCommandLib/UefiShellCommandLib.inf
  sp17|ShellPkg/Library/UefiShellDebug1CommandsLib/UefiShellDebug1CommandsLib.inf
  sp18|ShellPkg/Library/UefiShellDriver1CommandsLib/UefiShellDriver1CommandsLib.inf
  sp19|ShellPkg/Library/UefiShellInstall1CommandsLib/UefiShellInstall1CommandsLib.inf
  sp20|ShellPkg/Library/UefiShellLevel1CommandsLib/UefiShellLevel1CommandsLib.inf
  sp21|ShellPkg/Library/UefiShellLevel2CommandsLib/UefiShellLevel2CommandsLib.inf
  sp22|ShellPkg/Library/UefiShellLevel3CommandsLib/UefiShellLevel3CommandsLib.inf
  sp23|ShellPkg/Library/UefiShellLib/UefiShellLib.inf
  sp24|ShellPkg/Library/UefiShellNetwork1CommandsLib/UefiShellNetwork1CommandsLib.inf
  sp25|ShellPkg/Library/UefiShellNetwork2CommandsLib/UefiShellNetwork2CommandsLib.inf
  sl1|StdLib/BsdSocketLib/BsdSocketLib.inf
  sl2|StdLib/EfiSocketLib/EfiSocketLib.inf
  sl3|StdLib/LibC/Containers/ContainerLib.inf
  sl4|StdLib/LibC/Ctype/Ctype.inf
  sl5|StdLib/LibC/gdtoa/gdtoa.inf
  sl6|StdLib/LibC/LibC.inf
  sl7|StdLib/LibC/Locale/Locale.inf
  sl8|StdLib/LibC/Math/Math.inf
  sl9|StdLib/LibC/NetUtil/NetUtil.inf
  sl10|StdLib/LibC/Signal/Signal.inf
  sl11|StdLib/LibC/Softfloat/Softfloat.inf
  sl12|StdLib/LibC/Stdio/Stdio.inf
  sl13|StdLib/LibC/StdLib/StdLib.inf
  sl14|StdLib/LibC/String/String.inf
  sl15|StdLib/LibC/Time/Time.inf
  sl16|StdLib/LibC/Uefi/Devices/daConsole.inf
  sl17|StdLib/LibC/Uefi/Devices/daShell.inf
  sl18|StdLib/LibC/Uefi/Devices/daUtility.inf
  sl19|StdLib/LibC/Uefi/InteractiveIO/IIO.inf
  sl20|StdLib/LibC/Uefi/Uefi.inf
  sl21|StdLib/LibC/Wchar/Wchar.inf
  sl22|StdLib/PosixLib/Err/LibErr.inf
  sl23|StdLib/PosixLib/Gen/LibGen.inf
  sl24|StdLib/PosixLib/Glob/LibGlob.inf
  sl25|StdLib/PosixLib/PosixLib.inf
  sl26|StdLib/PosixLib/Stringlist/LibStringlist.inf
  sl27|StdLib/SocketDxe/SocketDxe.inf
  sl28|StdLib/UseSocketDxe/UseSocketDxe.inf
  ep1|EmbeddedPkg/Application/AndroidBoot/AndroidBootApp.inf
  ep2|EmbeddedPkg/Application/AndroidFastboot/AndroidFastbootApp.inf
  ep3|EmbeddedPkg/Drivers/AndroidFastbootTransportTcpDxe/FastbootTransportTcpDxe.inf
  ep4|EmbeddedPkg/Drivers/AndroidFastbootTransportUsbDxe/FastbootTransportUsbDxe.inf
  ep5|EmbeddedPkg/Drivers/ConsolePrefDxe/ConsolePrefDxe.inf
  ep6|EmbeddedPkg/Drivers/DtPlatformDxe/DtPlatformDxe.inf
  ep7|EmbeddedPkg/Drivers/FdtClientDxe/FdtClientDxe.inf
  ep8|EmbeddedPkg/Drivers/NonCoherentIoMmuDxe/NonCoherentIoMmuDxe.inf
  ep9|EmbeddedPkg/Drivers/VirtualKeyboardDxe/VirtualKeyboardDxe.inf
  ep10|EmbeddedPkg/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
  ep11|EmbeddedPkg/GdbStub/GdbStub.inf
  ep12|EmbeddedPkg/Library/AcpiLib/AcpiLib.inf
  ep13|EmbeddedPkg/Library/AndroidBootImgLib/AndroidBootImgLib.inf
  ep14|EmbeddedPkg/Library/CoherentDmaLib/CoherentDmaLib.inf
  ep15|EmbeddedPkg/Library/DebugAgentTimerLibNull/DebugAgentTimerLibNull.inf
  ep16|EmbeddedPkg/Library/DxeDtPlatformDtbLoaderLibDefault/DxeDtPlatformDtbLoaderLibDefault.inf
  ep17|EmbeddedPkg/Library/FdtLib/FdtLib.inf
  ep18|EmbeddedPkg/Library/GdbSerialDebugPortLib/GdbSerialDebugPortLib.inf
  ep19|EmbeddedPkg/Library/GdbSerialLib/GdbSerialLib.inf
  ep20|EmbeddedPkg/Library/NonCoherentDmaLib/NonCoherentDmaLib.inf
  ep21|EmbeddedPkg/Library/NorFlashInfoLib/NorFlashInfoLib.inf
  ep22|EmbeddedPkg/Library/NvVarStoreFormattedLib/NvVarStoreFormattedLib.inf
  ep23|EmbeddedPkg/Library/PlatformHasAcpiLib/PlatformHasAcpiLib.inf
  ep24|EmbeddedPkg/Library/PrePiExtractGuidedSectionLib/PrePiExtractGuidedSectionLib.inf
  ep25|EmbeddedPkg/Library/PrePiHobLib/PrePiHobLib.inf
  ep26|EmbeddedPkg/Library/PrePiLib/PrePiLib.inf
  ep27|EmbeddedPkg/Library/PrePiMemoryAllocationLib/PrePiMemoryAllocationLib.inf
  ep28|EmbeddedPkg/Library/TemplateRealTimeClockLib/TemplateRealTimeClockLib.inf
  ep29|EmbeddedPkg/Library/TemplateResetSystemLib/TemplateResetSystemLib.inf
  ep30|EmbeddedPkg/Library/TimeBaseLib/TimeBaseLib.inf
  ep31|EmbeddedPkg/Library/VirtualRealTimeClockLib/VirtualRealTimeClockLib.inf
  ep32|EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
  ep33|EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
  ep34|EmbeddedPkg/ResetRuntimeDxe/ResetRuntimeDxe.inf
  ep35|EmbeddedPkg/SimpleTextInOutSerial/SimpleTextInOutSerial.inf
  ep36|EmbeddedPkg/Universal/MmcDxe/MmcDxe.inf
  ap1|ArmPkg/Drivers/ArmCrashDumpDxe/ArmCrashDumpDxe.inf
  ap2|ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
  ap3|ArmPkg/Drivers/ArmGic/ArmGicLib.inf
  ap4|ArmPkg/Drivers/ArmPciCpuIo2Dxe/ArmPciCpuIo2Dxe.inf
  ap5|ArmPkg/Drivers/ArmScmiDxe/ArmScmiDxe.inf
  ap6|ArmPkg/Drivers/CpuDxe/CpuDxe.inf
  ap7|ArmPkg/Drivers/CpuPei/CpuPei.inf
  ap8|ArmPkg/Drivers/GenericWatchdogDxe/GenericWatchdogDxe.inf
  ap9|ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.inf
  ap10|ArmPkg/Drivers/TimerDxe/TimerDxe.inf
  ap11|ArmPkg/Filesystem/SemihostFs/SemihostFs.inf
  ap12|ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib.inf
  ap13|ArmPkg/Library/ArmCacheMaintenanceLib/ArmCacheMaintenanceLib.inf
  ap14|ArmPkg/Library/ArmDisassemblerLib/ArmDisassemblerLib.inf
  ap15|ArmPkg/Library/ArmExceptionLib/ArmExceptionLib.inf
  ap16|ArmPkg/Library/ArmExceptionLib/ArmRelocateExceptionLib.inf
  ap17|ArmPkg/Library/ArmGenericTimerPhyCounterLib/ArmGenericTimerPhyCounterLib.inf
  ap18|ArmPkg/Library/ArmGenericTimerVirtCounterLib/ArmGenericTimerVirtCounterLib.inf
  ap19|ArmPkg/Library/ArmGicArchLib/ArmGicArchLib.inf
  ap20|ArmPkg/Library/ArmGicArchSecLib/ArmGicArchSecLib.inf
  ap21|ArmPkg/Library/ArmHvcLib/ArmHvcLib.inf
  ap22|ArmPkg/Library/ArmLib/ArmBaseLib.inf
  ap23|ArmPkg/Library/ArmMmuLib/ArmMmuBaseLib.inf
  ap24|ArmPkg/Library/ArmMmuLib/ArmMmuPeiLib.inf
  ap25|ArmPkg/Library/ArmMtlNullLib/ArmMtlNullLib.inf
  ap26|ArmPkg/Library/ArmPsciResetSystemLib/ArmPsciResetSystemLib.inf
  ap27|ArmPkg/Library/ArmSmcLib/ArmSmcLib.inf
  ap28|ArmPkg/Library/ArmSmcLibNull/ArmSmcLibNull.inf
  ap29|ArmPkg/Library/ArmSmcPsciResetSystemLib/ArmSmcPsciResetSystemLib.inf
  ap30|ArmPkg/Library/ArmSoftFloatLib/ArmSoftFloatLib.inf
  ap31|ArmPkg/Library/ArmSvcLib/ArmSvcLib.inf
  ap32|ArmPkg/Library/CompilerIntrinsicsLib/CompilerIntrinsicsLib.inf
  ap33|ArmPkg/Library/DebugAgentSymbolsBaseLib/DebugAgentSymbolsBaseLib.inf
  ap34|ArmPkg/Library/DebugPeCoffExtraActionLib/DebugPeCoffExtraActionLib.inf
  ap35|ArmPkg/Library/DefaultExceptionHandlerLib/DefaultExceptionHandlerLib.inf
  ap36|ArmPkg/Library/LinuxBootBootManagerLib/LinuxBootBootManagerLib.inf
  ap37|ArmPkg/Library/OpteeLib/OpteeLib.inf
  ap38|ArmPkg/Library/PeiServicesTablePointerLib/PeiServicesTablePointerLib.inf
  ap39|ArmPkg/Library/PlatformBootManagerLib/PlatformBootManagerLib.inf
  ap40|ArmPkg/Library/RvdPeCoffExtraActionLib/RvdPeCoffExtraActionLib.inf
  ap41|ArmPkg/Library/SemiHostingDebugLib/SemiHostingDebugLib.inf
  ap42|ArmPkg/Library/SemiHostingSerialPortLib/SemiHostingSerialPortLib.inf
  ap43|ArmPkg/Library/SemihostLib/SemihostLib.inf
  ap44|ArmPkg/Library/StandaloneMmMmuLib/ArmMmuStandaloneMmLib.inf
  ap45|ArmPkg/Universal/Smbios/OemMiscLibNull/OemMiscLibNull.inf
  ap46|ArmPkg/Universal/Smbios/ProcessorSubClassDxe/ProcessorSubClassDxe.inf
  ap47|ArmPkg/Universal/Smbios/SmbiosMiscDxe/SmbiosMiscDxe.inf

[Components]
  Edk2LibcForDotNet/Edk2LibcForDotNet.inf
